import 'package:bloc_example/database/app_database.dart';
import 'package:drift/drift.dart' as drift;
import 'package:injectable/injectable.dart';

// The abstract repository defining the contract.
// We use the 'Post' class generated by Drift, so we export it from the database file.
export 'package:bloc_example/database/app_database.dart' show Post;

abstract class PostRepository {
  Future<List<Post>> fetchPosts();
  Future<Post?> fetchPostDetails(int postId);
  Future<void> addPost(String title, String content);
  Future<void> editPost({required int id, required String title, required String content});
  Future<void> deletePost(int postId);
}

// A concrete implementation using the Drift database
@LazySingleton(as: PostRepository)
class DriftPostRepository implements PostRepository {
  final AppDatabase _database;

  DriftPostRepository(this._database);

  @override
  Future<List<Post>> fetchPosts() {
    return _database.getAllPosts();
  }

  @override
  Future<Post?> fetchPostDetails(int postId) {
    return _database.getPostById(postId);
  }

  @override
  Future<void> addPost(String title, String content) async {
    final post = PostsCompanion(
      title: drift.Value(title),
      content: drift.Value(content),
    );
    await _database.insertPost(post);
  }

  @override
  Future<void> editPost({required int id, required String title, required String content}) async {
    final post = PostsCompanion(
      id: drift.Value(id),
      title: drift.Value(title),
      content: drift.Value(content),
    );
    await _database.updatePost(post);
  }

  @override
  Future<void> deletePost(int postId) async {
    await _database.deletePost(postId);
  }
}